---
- hosts: all
  remote_user: marcos
  become: true
  become_user: root
  become_method: sudo
  roles:
    - { role: role-base, user: "marcos", sshkey: "/home/marcos/.ssh/id_rsa.pub", sshroot: False }
